#! /bin/sh

# Keybinding
pgrep -x sxhkd >/dev/null || sxhkd &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &

# gestures
libinput-gestures-setup autostart start

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap 8
bspc config top_padding 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Autoload
polybar --reload main &
xbindkeys &
~/.fehbg &
picom &
flameshot &
nm-applet &
pa-applet &
xinput disable 11 # disable touch screen
blueman-applet &

# Redefine keys
setxkbmap -option caps:ctrl_modifier &
# redefine page up/down on lenovo keyboard
xmodmap -e 'keycode 112 = Left'
xmodmap -e 'keycode 117 = Right'
