#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Screenkey manage=off

## Autostart
sh $HOME/.config/polybar/bspwm.sh
xbindkeys&
#picom --experimental-backends --backend glx --xrender-sync-fence &
~/.fehbg &
setxkbmap -option caps:ctrl_modifier &
#dunst &
