#!/usr/bin/env bash

git clone https://github.com/pyenv/pyenv.git ~/.pyenv
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
git clone https://github.com/rbenv/rbenv.git ~/.rbenv

mkdir -p ~/.rbenv/plugins
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

~/.pyenv/bin/pyenv install 3.10.1
~/.pyenv/bin/pyenv global 3.10.1
pip install --upgrade pip
pip install neovim ranger-fm

NVM_DIR="$HOME/.nvm"
source $NVM_DIR/nvm.sh 

nvm install --lts
npm -g install diff-so-fancy yarn neovim

~/.rbenv/bin/rbenv install 3.0.3
~/.rbenv/bin/rbenv global 3.0.3
eval "$(rbenv init - zsh)"
gem install neovim 

#sudo pacman -Ss ueberzug neovim xclip exa
