#!/usr/bin/env bash

PROJECT="$HOME/projects/dotfiles-linux/"

# install nvim, exa bat

# virtual environments
# pyenv
git clone https://github.com/pyenv/pyenv.git ~/.pyenv

# rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
mkdir -p "$(rbenv root)"/plugins
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

